import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class EmployeeService {


  employees = [
  {
    "id": 1,
    "firstName": "John",
    "lastName": "Doe",
    "birthDate": "1990",
    "sex": "Male",
    "email": "john.doe@example.com",
    "mobile": "1234567890",
    "address1": "123 Main St",
    "address2": "Apt 4B",
    "id_t2_1_country": "2",
    "id_t2_1_div1": "California",
    "id_t2_1_div2": "Los Angeles County",
    "id_t2_1_div3": "Los Angeles",
    "local": "Downtown",
    "zipCode": "90001",
    "branchId": "BR001",
    "branchName": "Downtown Branch",
    "sectionId": "BRANCH001",
    "sectionName": "Main Dining Area",
    "id_t5_1_m_user_roles": ["3"],
    "roleNames": ["Restaurant Manager"],
    "status": "active"
  },
  {
    "id": 2,
    "firstName": "Jane",
    "lastName": "Smith",
    "birthDate": "1985",
    "sex": "Female",
    "email": "jane.smith@example.com",
    "mobile": "0987654321",
    "address1": "456 Park Ave",
    "address2": "",
    "id_t2_1_country": "2",
    "id_t2_1_div1": "New York",
    "id_t2_1_div2": "Queens",
    "id_t2_1_div3": "Flushing",
    "local": "Murray Hill",
    "zipCode": "11354",
    "branchId": "BR001",
    "branchName": "Downtown Branch",
    "sectionId": "BRANCH002",
    "sectionName": "Outdoor Patio",
    "id_t5_1_m_user_roles": ["1"],
    "roleNames": ["Owner"],
    "status": "inactive"
  },
  {
    "id": 3,
    "firstName": "Carlos",
    "lastName": "Gonzalez",
    "birthDate": "1992",
    "sex": "Male",
    "email": "carlos.g@example.com",
    "mobile": "2223334444",
    "address1": "789 Ocean Dr",
    "address2": "",
    "id_t2_1_country": "2",
    "id_t2_1_div1": "California",
    "id_t2_1_div2": "Los Angeles County",
    "id_t2_1_div3": "Los Angeles",
    "local": "Colonia Americana",
    "zipCode": "44100",
    "branchId": "BR002",
    "branchName": "Uptown Branch",
    "sectionId": "BRANCH001",
    "sectionName": "Main Dining Area",
    "id_t5_1_m_user_roles": ["3"],
    "roleNames": ["Restaurant Manager"],
    "status": "active"
  },
  {
    "id": 4,
    "firstName": "Aisha",
    "lastName": "Khan",
    "birthDate": "1995",
    "sex": "Female",
    "email": "aisha.khan@example.com",
    "mobile": "5556667777",
    "address1": "12 Garden St",
    "address2": "",
    "id_t2_1_country": "1",
    "id_t2_1_div1": "Maharashtra",
    "id_t2_1_div2": "Mumbai",
    "id_t2_1_div3": "Andheri",
    "local": "Gulberg II",
    "zipCode": "54660",
    "branchId": "BR003",
    "branchName": "City Center Branch",
    "sectionId": "BRANCH003",
    "sectionName": "VIP Lounge",
    "id_t5_1_m_user_roles": ["3"],
    "roleNames": ["Restaurant Manager"],
    "status": "active"
  },
  {
    "id": 5,
    "firstName": "Tom",
    "lastName": "Hanks",
    "birthDate": "1960",
    "sex": "Male",
    "email": "tom.h@example.com",
    "mobile": "4445556666",
    "address1": "500 Hollywood Blvd",
    "address2": "",
    "id_t2_1_country": "2",
    "id_t2_1_div1": "California",
    "id_t2_1_div2": "Los Angeles County",
    "id_t2_1_div3": "Beverly Hills",
    "local": "North Beverly",
    "zipCode": "90210",
    "branchId": "BR003",
    "branchName": "City Center Branch",
    "sectionId": "BRANCH001",
    "sectionName": "Main Dining Area",
    "id_t5_1_m_user_roles": ["3"],
    "roleNames": ["Restaurant Manager"],
    "status": "inactive"
  },
  {
    "id": 6,
    "firstName": "Emily",
    "lastName": "Wong",
    "birthDate": "1998",
    "sex": "Female",
    "email": "emily.wong@example.com",
    "mobile": "7778889999",
    "address1": "88 Lotus Rd",
    "address2": "",
    "id_t2_1_country": "3",
    "id_t2_1_div1": "Ontario",
    "id_t2_1_div2": "Toronto",
    "id_t2_1_div3": "North York",
    "local": "Shekou",
    "zipCode": "518067",
    "branchId": "BR004",
    "branchName": "Lakeside Branch",
    "sectionId": "BRANCH004",
    "sectionName": "Main Hall",
    "id_t5_1_m_user_roles": ["1"],
    "roleNames": ["Owner"],
    "status": "active"
  },
  {
    "id": 7,
    "firstName": "David",
    "lastName": "Lee",
    "birthDate": "1982",
    "sex": "Male",
    "email": "david.lee@example.com",
    "mobile": "1112223333",
    "address1": "901 King St",
    "address2": "Suite 101",
    "id_t2_1_country": "3",
    "id_t2_1_div1": "Ontario",
    "id_t2_1_div2": "Toronto",
    "id_t2_1_div3": "North York",
    "local": "Willowdale",
    "zipCode": "M2N 5N5",
    "branchId": "BR004",
    "branchName": "Lakeside Branch",
    "sectionId": "BRANCH004",
    "sectionName": "Main Hall",
    "id_t5_1_m_user_roles": ["3"],
    "roleNames": ["Restaurant Manager"],
    "status": "active"
  },
  {
    "id": 8,
    "firstName": "Fatima",
    "lastName": "Al-Zahra",
    "birthDate": "1993",
    "sex": "Female",
    "email": "fatima.zahra@example.com",
    "mobile": "8887776666",
    "address1": "22 Palm Crescent",
    "address2": "",
    "id_t2_1_country": "1",
    "id_t2_1_div1": "Maharashtra",
    "id_t2_1_div2": "Pune",
    "id_t2_1_div3": "Andheri",
    "local": "Rigga Road",
    "zipCode": "00000",
    "branchId": "BR004",
    "branchName": "Lakeside Branch",
    "sectionId": "BRANCH004",
    "sectionName": "Main Hall",
    "id_t5_1_m_user_roles": ["3", "1"],
    "roleNames": ["Restaurant Manager", "Owner"],
    "status": "active"
  },
  {
    "id": 9,
    "firstName": "Liam",
    "lastName": "O'Connor",
    "birthDate": "1987",
    "sex": "Male",
    "email": "liam.oconnor@example.com",
    "mobile": "3334445555",
    "address1": "17 Dublin Rd",
    "address2": "",
    "id_t2_1_country": "2",
    "id_t2_1_div1": "California",
    "id_t2_1_div2": "Los Angeles County",
    "id_t2_1_div3": "Los Angeles",
    "local": "Smithfield",
    "zipCode": "D07",
    "branchId": "BR001",
    "branchName": "Downtown Branch",
    "sectionId": "BRANCH001",
    "sectionName": "Main Dining Area",
    "id_t5_1_m_user_roles": ["1"],
    "roleNames": ["Owner"],
    "status": "inactive"
  },
  {
    "id": 10,
    "firstName": "Sakura",
    "lastName": "Tanaka",
    "birthDate": "1991",
    "sex": "Female",
    "email": "sakura.t@example.com",
    "mobile": "9990001111",
    "address1": "3-5-2 Shibuya",
    "address2": "",
    "id_t2_1_country": "2",
    "id_t2_1_div1": "California",
    "id_t2_1_div2": "Los Angeles County",
    "id_t2_1_div3": "Los Angeles",
    "local": "Harajuku",
    "zipCode": "150-0001",
    "branchId": "BR002",
    "branchName": "Uptown Branch",
    "sectionId": "BRANCH002",
    "sectionName": "Outdoor Patio",
    "id_t5_1_m_user_roles": ["3"],
    "roleNames": ["Restaurant Manager"],
    "status": "active"
  }
]

  constructor() { }


  getAllEmployees(){
    return this.employees;
  }
}
